SPLIT_KEYBOARD = yes
SERIAL_DRIVER = usart
MCU = STM32F411
BOARD = GENERIC_STM32_F411XE
BOOTMAGIC_ENABLE = yes
EXTRAKEY_ENABLE = yes

COMBO_ENABLE = yes
CAPS_WORD_ENABLE = yes
SRC += features/achordion.c
